### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by shelbourn** [shelbourn/JavaFX-Inventory-Management-Project#12]
- [x] Remove Unnecessary File Imports
- [x] Remove Unnecessary JavaFX IDs
- [x] Comment Code for Reviewers
- [x] Add SYSOUT Comments for all IO Ops
- [x] Restructure Code (It's a MESS right now) 😠 
- [x] Change naming conventions for Scene creation
- [x] Move Exception Handling for Controllers into a separate class
